### ISSUE TITLE
[BUG] Typing an import in a file other than the storyboard will bring down the editor

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1131]
Sample project: https://utopia.pizza/p/5585651d-cant-import-this/ - try uncommenting and completing the import statement on line 4 of `app.js`

Whilst trying to write an import statement in any file other than the storyboard file, the editor will crash during module resolution as soon as you start writing the path for the import, with the error:

```
RangeError: Maximum call stack size exceeded
    at indexJsPath (module-resolution.ts:188)
    at failoverResolveResults (module-resolution.ts:32)
    at resolveNonRelativeModule (module-resolution.ts:186)
    at eval (module-resolution.ts:198)
    at failoverResolveResults (module-resolution.ts:32)
    at resolveNonRelativeModule (module-resolution.ts:186)
    at resolveModule (module-resolution.ts:223)
    at Object.resolveModulePath (module-resolution.ts:229)
    at Object.eval [as resolve] (package-manager.ts:21)
    at eval (editor-state.ts:249)
```

I highly suspect this is related to #1082

**Comment by maltenuhn** [comment]
Seems like this was fixed along with #1082 as you suspected @Rheeseyb - we now get the correct error message here while the statement is incomplete...
![image](https://user-images.githubusercontent.com/2945037/116477183-2aa41080-a874-11eb-888e-40507a58f8b4.png)

... and completing it works as expected:
![image](https://user-images.githubusercontent.com/2945037/116477332-5d4e0900-a874-11eb-8781-e2b910ead285.png)

**Comment by maltenuhn** [comment]
I'm still unable to reproduce this. I'll close it.  @Rheeseyb - do resurrect if there's a repro case I'm unaware of!

**Comment by Rheeseyb** [comment]
:+1: I'm pretty certain this was fixed by #1162

**Comment by enidemi** [comment]
I can still see the error when manually writing an import statement, as it reaches the first `/` before the src in the path it throws an error.

**Comment by Rheeseyb** [comment]
Yep, confirmed, it is indeed still a bug. Re-opening
